spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
####################### mybatis ###################################   
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.formssi.bean
  mapper-locations: mybatis/*Mapper.xml
####################### log ###################################     
logging:
  config: classpath:logback-spring.xml
  level: 
    com.formssi: debug
    
####################### shiro ###################################
shiro: 
  config:
  #可匿名访问的api关键字
    anon: swagger,docs,/login,/getSpecificPostInfo,/getNewestPost,/updateKpiBalance,/sendVericationCodeForReg,/sendVericationCode,/register,/modifyPassword,/existUser
    #authc: /member/**
    #logoutUrl: /logout
    #loginUrl: /login
    #successUrl: /sp
    #unauthorizedUrl: /unauthorized
    algorithmName: md5
    hashIterations: 2   
     
####################### tomcat ################################### 
server:
  tomcat:
    max-threads: 1000
    max-connections: 1000