####################### server info ################################### 
server:
  #address: 192.168.31.202
  port: 9001      
####################### datasource ###################################   
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kpi?characterEncoding:utf8
    username: test
    password: 123456
####################### redis ################################### 
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 5000
    pool:
      max-idle: 10
      min-idle: 0
      max-active: 100
      max-wait: 100000
################################CORS Header#######################
response: 
  headerMap:
    Access-Control-Allow-Origin: http://localhost:8081
    Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE
    Access-Control-Max-Age: 3600
    Access-Control-Allow-Headers: authorization, content-type
    Access-Control-Allow-Credentials: true
    Content-Type: application/x-www-form-urlencoded; charset=UTF-8
    Accss-Control-Expose-Headers: Content-Disposition
################################log#######################
log: 
  path: D:/splog/kpidev/logs